### ISSUE TITLE
How to get debug info

### ISSUE THREAD

**Issue by ywarnier** [gflohr/Template-Plugin-Gettext#10]
Hi, and thanks for developing this module!

I'm trying to integrate it into a series of TT files in a working application, but I'm hitting a few issues I would love to get some guidance with.

The example you give in your README.md file with "BEGIN", and this line of code using the given "@search_dirs", are a bit tricky for me:
https://github.com/gflohr/Template-Plugin-Gettext/blob/bb258988f3bbce1c6aaf85af35e811d362f655ef/lib/Template/Plugin/Gettext.pm#L72

In my case, I am sharing my Template module between different applications on the same system, but my language files are inside each applications' root directory. As such, I am not able to define an additional fixed common path for all my TT files (from my different applications) to add to the include path, because I would have to modify my shared Template module each time I add an application.

On the other side, I don't want to modify each and every TT file to include something like this:
```
[% USE gtx = Gettext('my-app', lang, 'utf-8', '/var/www/' _ app_path _ '/locale') %]
```
...mostly because I have many TT files.

*But* I have the `domain`, `language` and `app_path` variables inside my Template module.

So I'm looking for a solution that would allow me to pre-load Template::Plugin::Gettext from inside my module (before calling $template->process()) based on these variables.

Something like this, maybe:
```
my $gtx = new Gettext('domain', $lang, 'utf-8', '/var/www/'.$app_path.'/locale');
my $data = {
  config => $config,
  gtx => $gtx,
  ...
};
$template->process($file, $data);
```
Is there something that would allow me to do that at the moment? I'm not a Perl developer, strictly speaking, and I'm having a hard time finding that.

I've tried it and it doesn't shout any error but there's nothing coming out of a `[% gtx.gettext('var') %]` either, so this brings the second issue: is there a way to print some debug info about what the plugin is seeing (like if it really found some .mo/.po files and where)?

If it is not there, would you be open to including a PR with those options and publish a new version with it?

**Comment by gflohr** [comment]
Hi,

the code example with `@search_dirs` explains how the default search path for the mo files is assembled.  That doesn't help you here.

Inserting the line with `[% USE %]` into each and every template would basically solve your problem.  You should be aware, though, that the lookup of the `.mo` catalogs is cached.  So you need different textdomains *and* paths.  Once the catalog for a domain was successfully loaded, all search paths are ignored because the data is already in memory.

Instantiating the template from Perl instead of from inside your templates is not possible.  Template Toolkit instantiates plugins with a [`Template::Context`](http://search.cpan.org/~abw/Template-Toolkit-2.27/lib/Template/Context.pm) and you don't have that object at that time.

The function you are looking for is probably [`Locale::Messages::bindtextdomain()`](http://search.cpan.org/~guido/libintl-perl-1.29/lib/Locale/Messages.pm#bindtextdomain) which allows you to map a text domain to a search directory.  You can call that function from inside your template but you will rather want to do that in your Perl code:

```perl
use Locale::Messages qw(bindtextdomain);
use POSIX;

# Select the most forgiving backend.
Locale::Message->select_package('gettext_dumb');

# Map (bind) the domain to a specific locale directory.
bindtextdomain $domain, '/var/www/' . $app_path . '/locale';
$template->process($file, $data);
```

Important! The variable `$domain` must be different for each of your applications, see above.

Debugging these kinds of problems is tricky.  `T::P::Gettext` is based on https://github.com/gflohr/libintl-perl which is - depending on your particular setup - in turn based on functionality implemented in C.  The call to `Locale::Messages->select_package('gettext_dumb')` above avoids most of the problems with C code but there are still enough pitfalls.

The best way to provide better diagnostics would probably be to add a debugging function to the underlying `Locale::Messages`.  I have an idea for that but I need time for implementing it.

**Comment by gflohr** [comment]
I think I can close that, right? Otherwise, just feel free to reopen it.
