### ISSUE TITLE
xgettext-tt2 finds nothing

### ISSUE THREAD

**Issue by jvolkening** [gflohr/Template-Plugin-Gettext#2]
I tried to implement i18n in my TT templates using this module, but quickly ran into the issue that `xgettext-tt2` doesn't recognize any translatable strings in my templates. I then tried running it on a barebones example from the module POD:

```
<!-- test.tt -->
[% USE Gettext('com.textdomain.my', 'fr', 'utf-8') %]
[% Gettext.gettext('Hello, world!) %]
```

and then

```
xgettext-tt2 test.tt --force-po
```

but the output file is a skeleton only with no actual strings. Any guidance would be appreciated.

**Comment by gflohr** [comment]
xgettext-tt2 does leaves complaints about syntax errors to Template Toolkit.  You are missing the closing single quote after 'Hello, world!>>>'<<<.  Adding the quote fixes the problem.

**Comment by jvolkening** [comment]
Thanks. That example was copied from the POD so it looks like there are a few quotes missing there.

However, my original problem still remains. `xgettext-tt2` properly parses

```
[% USE Gettext('com.textdomain.my', 'fr', 'utf-8') %]
[% Gettext.gettext('Hello, world!') %]
```
but not
```
[% USE Gettext('com.textdomain.my', 'fr', 'utf-8') %]
[% 'Hello, world!' | gettext %]
```

Is the second syntax supported by the parser? Also, how do I enable verbose output from `xgettext-tt2` so I can see the syntax error messages you mention above? I don't see a relevant argument in the manpage.

Thanks for the help.

**Comment by gflohr** [comment]
That is a bug (see #4).  Thanks for reporting.  It is fixed in 7e5a468, test cases added.  I have also corrected the missing single quote in the docs.

Temporary workaround for the filter problem:

    [% 'Hello, world!' | gettext() %]

In other words, add empty parentheses.

There is no option to activate verbose syntax errors.  `xgettext-tt2` does pretty much the same with TT files what GNU `xgettext` does with source files in C or any of the other supported languages.  It tries its best to extract translatable strings from the sources, and leaves complaints to the real compiler, even if the source are complete gibberish, or syntactically wrong.

This plug-in does not really parse the templates.  It invokes the Template Toolkit parser on them but intercepts the token stream, extracts the relevant method/filter invocations and the returns an empty token stream to the Template Toolkit, so that it does not attempt to follow INCLUDE directives or so.

Even if I wrote a full-fledged parser for templates, I don't think that it would be wise to use it for message extraction.  Template Toolkit does not have a formal grammar, and that approach would therefore always imply the risk of misinterpreting input.  My "interception" approach relies almost entirely on the TT parser that ultimately compiles and renders the templates.

I think, this is okay for practical purposes.  because normally you will first check whether your templates compile and render alright before you start extracting strings.

Similar problems can arise at run-time.  If you forget to "USE" the plug-in or have a typo in a method name, you will hardly get an error message but that is how the Template Toolkit works.  It is very forgiving.

Thanks for your interest in the software!

**Comment by jvolkening** [comment]
Thanks for the quick reply. I will pull the latest version and give it a try when time permits.

**Comment by gflohr** [comment]
No problem.

Just in case that you have gained the impression that the plug-in is completely unstable ... I run several web sites that use it, for example www.qgoda.net.  The complete sources are on github: https://github.com/gflohr/qgoda-site

Templates can be found at https://github.com/gflohr/qgoda-site/tree/master/_views and https://github.com/gflohr/qgoda-site/tree/master/_includes, the PO directory is at https://github.com/gflohr/qgoda-site/tree/master/_po although the vast majority of the PO entries come from Markdown content and not from TT2 templates.

The German translation is incomplete but for example http://www.qgoda.net/de/docs/unterschiede-zu-jekyll/ can serve as a proof-of-concept.

**Comment by jvolkening** [comment]
> Just in case that you have gained the impression that the plug-in is completely unstable ... I run several web sites that use it, for example www.qgoda.net

I'm willing to give it a go. I am developing a site which will eventually go into production and for which i18n is very important, but I have not dealt with this previously. I spent four hours yesterday combing through CPAN and trying at least three different packages to get a working prototype, and nothing has yet worked properly. Your package is the closest I have come to success, and I like that the code footprint within my templates is minimal and that is is under active development. I ended up just setting up a custom TT2 filter with a hash table lookup for translations, but I would really like to plug into a more standard framework so that the translation files are more reusable in the future.

I am still having an issue with T::P::G not recognizing or not liking my locales. For instance, I have generated the `*.po`/`*.mo` files for a Spanish translation under the 'es' directory, but the translation only works if I change the directory name to 'en_US' (the default locale on my system). I am passing the desired locale explicity in the `USE` statement and can confirm that T::P::G is receiving it correctly. I _believe_ the issue arises at the point where `POSIX::setlocale` is called and can't find an 'es' locale on my local system, so returns an undefined value. However, I have not finished tracking this and am not sure about it. I will open a separate issue once I have spent more time investigating, unless of course I manage to resolve it before then.

**Comment by gflohr** [comment]
T::P::G is based on libintl-perl which in turn is based (by default) on the GNU gettext runtime and that fails to retrieve translations if the corresponding locale is not installed on your system.

Before you invoke Template(3pm), add this to your code:

    use Locale::Messages;
    Locale::Messages->select_package('gettext_dumb');

See http://search.cpan.org/~guido/libintl-perl/lib/Locale/gettext_dumb.pm for the dilemma ...
